rcsoccersim installation script
robocin/scripts-ubuntu-common pull request #2
Opened 2023-01-14 20:46 UTC by Pvcunha

script for installation of rcsoccersim modules (rcssserver and rcssmonitor)

2023-01-15 16:38 UTC, joseviccruz reviewed
Testei a instalação em um container limpo com as sugestões e aparentemente instalou direitinho. Rodando os binários gerados deu isso:

```bash
$ ./rcsoccersim 
>>> Error: rcssserver can not be found in your PATH

$ ./rcssserver 
>>> rcssserver-17.0.1
>>> 
>>> Copyright (C) 1995, 1996, 1997, 1998, 1999 Electrotechnical Laboratory.
>>> 2000 - RoboCup Soccer Simulator Maintenance Group.
>>> 
>>> Simulator Random Seed: 1673800628
>>> CSVSaver: Ready
>>> STDOutSaver: Ready
>>> Using simulator's random seed as Hetero Player Seed: 1673800628
>>> wind factor: rand: 0.000000, vector: (0.000000, 0.000000)
>>> logger.cpp: 329: can't open the game log file ./incomplete.rcg

$ ./rcssclient 
>>> Hit Ctrl-C to exit.
```

É o comportamento esperado?

2023-01-15 16:38 UTC, joseviccruz commented on rcsoccersim.sh
> +  mv $package_name /opt
```suggestion
  local tmp_dir="/tmp/${package_name}"
  local git_url="$GITHUB_RCSOCCERSIM_PREFIX/${package_name}.git"

  rm -rf "${tmp_dir}"
  mkdir -p "${tmp_dir}"

  git clone "${git_url}" -o "${package_name}" "${tmp_dir}"
  pushd "${tmp_dir}" || exit 1
  ./bootstrap && ./configure --prefix "/opt/${package_name}" && make -j"$(nproc)" && make install
  popd || exit 1

  rm -rf "${tmp_dir}"
```

2023-01-15 16:38 UTC, joseviccruz commented on rcsoccersim.sh
> +
```suggestion

echo -e "\x1B[01;93mInstalling required deps...\n\u001b[0m"
# reference: https://github.com/rcsoccersim/rcssserver#soccer-quick-start
apt install build-essential automake autoconf libtool flex bison -y

```

flex e bison não vem por default, acabou sendo um engano da minha parte, os demais já foram instalados, mas gente usa os do sistema em todo canto. boost tem seu próprio script, dessa forma tirei daqui

2023-01-15 20:12 UTC, Pvcunha commented on rcsoccersim.sh
> +
Eu ia fazer o próprio script pro flex e pro bison também

2023-01-16 18:45 UTC, joseviccruz commented on rcsoccersim.sh
> +
> Eu ia fazer o próprio script pro flex e pro bison também

Show de bola

2023-01-17 16:54 UTC, joseviccruz approved these changes

2023-01-17 18:02 UTC, Pvcunha commented
> Testei a instalação em um container limpo com as sugestões e aparentemente instalou direitinho. Rodando os binários gerados deu isso:
> 
> ```shell
> $ ./rcsoccersim 
> >>> Error: rcssserver can not be found in your PATH
> 
> $ ./rcssserver 
> >>> rcssserver-17.0.1
> >>> 
> >>> Copyright (C) 1995, 1996, 1997, 1998, 1999 Electrotechnical Laboratory.
> >>> 2000 - RoboCup Soccer Simulator Maintenance Group.
> >>> 
> >>> Simulator Random Seed: 1673800628
> >>> CSVSaver: Ready
> >>> STDOutSaver: Ready
> >>> Using simulator's random seed as Hetero Player Seed: 1673800628
> >>> wind factor: rand: 0.000000, vector: (0.000000, 0.000000)
> >>> logger.cpp: 329: can't open the game log file ./incomplete.rcg
> 
> $ ./rcssclient 
> >>> Hit Ctrl-C to exit.
> ```
> 
> É o comportamento esperado?

nao, ele deveria conseguir rodar o binario a partir de qualquer lugar. Eh so dar o comando no terminal

2023-01-17 18:12 UTC, Pvcunha commented
> Eh so dar o comando no terminal. Isso no caso da instalacao padrao, mas eu nao sei quando a gente muda o diretorio de instalacao. Vou dar uma averiguada.

Eh preciso colocar o path do binario na variavel de ambiente PATH e rcsoccersim volta a funcionar.

2023-01-17 18:36 UTC, joseviccruz commented
> > Eh so dar o comando no terminal. Isso no caso da instalacao padrao, mas eu nao sei quando a gente muda o diretorio de instalacao. Vou dar uma averiguada.
> 
> Eh preciso colocar o path do binario na variavel de ambiente PATH e rcsoccersim volta a funcionar.

Acho que o melhor é fazer isso no dockerfile msm, é bem tranquilo

2023-01-18 00:25 UTC, fnalmeidap commented
- flex :heavy_check_mark: 
- bison :heavy_check_mark: 
- rcssserver :heavy_check_mark: 
- rcssmonitor :x: 

![image](https://user-images.githubusercontent.com/42683960/213046249-5624ee13-fcb4-4d64-b03b-d144cfcd40bb.png)

2023-01-18 00:26 UTC, fnalmeidap requested changes
O erro do monitor era esperado?

2023-01-18 15:13 UTC, Pvcunha commented
> O erro do monitor era esperado?

vou tentar descobrir hoje, eu tinha visto ele já. Vou comprar as libs pra imagem `pvcunha/robocin-2d:ubuntu-20.04` para essa. Mas esse arquivo que ele diz que ta faltando ta no caminho /opt/qt/5.15.2/lib, pelo que me recordo do que vi ontem... Enfim foi dar uma averiguada melhor

2023-01-18 15:56 UTC, Pvcunha commented
> > O erro do monitor era esperado?
> 
> vou tentar descobrir hoje, eu tinha visto ele já. Vou comparar as libs pra imagem `pvcunha/robocin-2d:ubuntu-20.04` para essa. Mas esse arquivo que ele diz que ta faltando ta no caminho /opt/qt/5.15.2/lib, pelo que me recordo do que vi ontem... Enfim foi dar uma averiguada melhor

O problema no qt eh o seguinte, os .so nao estao sendo achados pelo container. Como pode ser visto na imagem (ldd eh um comando pra verificar dependencias de shared libraries)
![image](https://user-images.githubusercontent.com/38233192/213220351-aee70675-cf90-47d4-aaf5-94f240ff1633.png)

Portanto o que precisa ser feito eh adicionar o path `/opt/qt/5.15.2/gcc_64/lib` para procurar por biblioteca nesse diretorio. Para isso ser feito basta adicionar uma linha ao arquivo `/etc/ld.so.conf.d/x86_64-linux-gnu.conf` contendo o path das bibliotecas do qt.
![image](https://user-images.githubusercontent.com/38233192/213221974-e4535712-9119-45af-af81-52f28b93da72.png)

Em seguida precisamos "atualizar" as bibliotecas do sistema com o comando `ldconfig`, e temos o seguinte output no comando `ldd`
![image](https://user-images.githubusercontent.com/38233192/213222670-77e7175c-1c2b-41c0-bf4e-75de77ab5798.png)

e por fim o output esperado do rcssmonitor por nao ter display disponivel ainda:
![image](https://user-images.githubusercontent.com/38233192/213223125-ebb16581-3b63-43c6-8321-4d0fb0b15461.png)

2023-01-19 12:41 UTC, fnalmeidap commented
Boa! 
Fico em dúvida de onde aplicar essa alteração, até onde sei esse problema só acontece conosco, então seria melhor usar apenas no nosso Dockerfile? Ideias @joseviccruz? :thought_balloon: 

De qualquer forma, vi que o script de instalação do QT tem a versão parametrizada, então apenas copiar este caminho para o .conf poderá causar problemas no futuro. A solução mais simples que penso é parametrizar o append da string com a versão do QT instalada no container:

```bash
export QTVERSION=$(ls /opt/qt/)
echo /opt/qt/$QTVERSION/gcc_64/lib >> /etc/ld.so.conf.d/x86_64-linux-gnu.conf 
ldconfig
```

2023-01-19 12:45 UTC, fnalmeidap approved these changes
Noice!
![image](https://user-images.githubusercontent.com/42683960/213446373-7c02bd57-96dc-43ae-a7aa-52146aa24ca5.png)

2023-01-19 13:56 UTC, Pvcunha commented
> Boa! Fico em dúvida de onde aplicar essa alteração, até onde sei esse problema só acontece conosco, então seria melhor usar apenas no nosso Dockerfile? Ideias @joseviccruz? thought_balloon

tem uma forma mais facil de fazer que eh adicionando o path da biblioteca para o LD_LIBRARY_PATH. Abri essa [issue](https://github.com/robocin/scripts-ubuntu-common/issues/3) e podemos continuar a discussao sobre isso por la.

2023-01-19 13:56 UTC, merged

2023-01-19 16:23 UTC, joseviccruz commented
> Boa! Fico em dúvida de onde aplicar essa alteração, até onde sei esse problema só acontece conosco, então seria melhor usar apenas no nosso Dockerfile? Ideias @joseviccruz? thought_balloon

Sim, por enquanto não considero bem um problema, podemos adicionar somente no dockerfile, mas vou investigar melhor dps.

Pq tipo, assim a gente pode ter multiplas versões de qt no sistema, e setar algum path assim pode quebrar essa funcionalidade